### ISSUE TITLE
Error with the token

### ISSUE THREAD

**Issue by notchars** [diwasatreya/Music-Bot#5]
I added an .env file with a token in it and it still doesn't work

![Image-Error](https://user-images.githubusercontent.com/86857592/146463286-abfaba08-42e6-4812-824b-b7ebf1daa753.png)
![Image-Error_1](https://user-images.githubusercontent.com/86857592/146463368-324879e4-ff96-49b7-b171-40b8061dad0c.png)

**Comment by ghost** [comment]
Edit line 185 in index.js to client.login("YOUR TOKEN");

**Comment by hisRoyalty** [comment]
Not a valid error
